name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Build, Test and Create JAR
      - name: Build with Maven
        run: mvn clean package

      # 4. Stop old application on EC2
      - name: Stop old application
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            if [ -f /home/ubuntu/app.pid ]; then

              PID=$(cat /home/ubuntu/app.pid)

              if kill -0 $PID 2>/dev/null; then
                echo "Stopping old application..."
                kill $PID
                sleep 5
              else
                echo "Old application is not running."
              fi

              rm -f /home/ubuntu/app.pid

            else
              echo "No previous application found."
            fi

      # 5. Upload JAR to EC2
      - name: Upload JAR to EC2
        if: github.event_name == 'push'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "target/demo-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/"
          overwrite: true

      # 6. Start new application on EC2
      - name: Start application on EC2
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Starting Spring Boot application..."

            nohup java -jar /home/ubuntu/demo-0.0.1-SNAPSHOT.jar \
              > /home/ubuntu/app.log 2>&1 &

            echo $! > /home/ubuntu/app.pid

            echo "Application started."
            echo "PID: $(cat /home/ubuntu/app.pid)"

            sleep 5

            echo "Checking application process..."

            if kill -0 $(cat /home/ubuntu/app.pid) 2>/dev/null; then
              echo "Spring Boot application is running successfully."
            else
              echo "Spring Boot application failed to start."
              echo "Application log:"
              tail -50 /home/ubuntu/app.log
              exit 1
            fi